<<<<<<< HEAD
"""add habit reminders
=======
"""describe the change
>>>>>>> cc30b236afbf34ce26a54add4ee6a06deec9f873

Revision ID: cd8260cedfba
Revises: 0001_initial
Create Date: 2026-07-15 00:17:05.307166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8260cedfba'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.add_column("habits", sa.Column("reminder_enabled", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("habits", sa.Column("reminder_time", sa.Time(), nullable=True))
=======
    pass
>>>>>>> cc30b236afbf34ce26a54add4ee6a06deec9f873
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.drop_column("habits", "reminder_time")
    op.drop_column("habits", "reminder_enabled")
=======
    pass
>>>>>>> cc30b236afbf34ce26a54add4ee6a06deec9f873
    # ### end Alembic commands ###
